# Generated by Django 2.0.2 on 2018-05-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cmnt_text',
            field=models.CharField(max_length=200),
        ),
    ]
