# Generated by Django 2.0.2 on 2018-05-27 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_auto_20180527_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
